name: Test Setup-Dotnet Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    test-dotnet:

        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
            
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '3'
            
            - name: Run Build
              run: |
                dotnet build
                echo "Build Complete"
